<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Shouldly" />
    <PackageReference Include="Spectre.Verify.Extensions" />
    <PackageReference Include="Verify" />
    <PackageReference Include="Verify.Xunit" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="coverlet.collector">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Wisp\Wisp.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Data\XRefStream.pdf" />
    <EmbeddedResource Include="Data\Simple.pdf" />
    <EmbeddedResource Include="Data\XRefStream.pdf" />
    <None Remove="Data\XRefStreamIncremental.pdf" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Expectations\" />
  </ItemGroup>

</Project>
