name: CI

on:
  push:
    tags:
      - '*'
    branches:
      - main
      - wip

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore
      run: dotnet restore -v normal
    - name: Build
      run: dotnet build -c Release --no-restore -v normal
    - name: Test
      run: dotnet test -c Release --no-restore --no-build -v normal
